### ISSUE TITLE
Error running utility program: Unable to create graph.png

### ISSUE THREAD

**Issue by nimec01** [fmidue/prolog-graph-lib#2]
There is an error when trying to generate the graph using the following scenario:

```prolog
/* program.pl */
append([], L , L ) .
append([H| T1 ] , L2 , [ H| T3 ] ) :- append (T1 , L2 , T3 ).
```
```bash
$ stack exec prolog-graph -- --file=program.pl -q "append([1,2],[3,4],[5,6])"
prolog-graph: Error running utility program: Unable to create graph.png
Unable to call the command  dot  with the arguments: " -Tpng " because of:  dot: runInteractiveProcess: posix_spawnp: does not exist (No such file or directory)
```

Is this due to some programs missing on my system (`README` at least does not mention any)?

I'm on an arm MacBook, if that's of interest.

**Comment by jvoigtlaender** [comment]
`dot` is an executable of https://graphviz.org/

And yes, GraphViz needs to be installed on the system. Should be added to the README. Feel free to make a pull request after confirming that installing GraphViz on your system solves the issue.

**Comment by nimec01** [comment]
Installing GraphViz indeed fixed this. Opened a pull request #3 .
